
const _kReleaseConfigModel = AppConfigModel(
  localApiUrls: {
    'mm': [
      "https://@{random}.vxtklsqhd.com",
      "https://@{random}.vzcumtkhp.com",
      "https://@{random}.vzxcpnmlk.com",
      "https://d16ox4lrcts7sd.cloudfront.net",
      "https://d1mfzjgb13rr1x.cloudfront.net",
      "https://d3daddgcsv5z1g.cloudfront.net",
      "https://d2c2w0p8sjz1o7.cloudfront.net",
      "https://dskntn5w2jbb4.cloudfront.net",
      "https://@{random}.wazumor.com",
      "https://@{random}.wberqxan.com",
      "https://@{random}.wbnfqz.com",
      "https://@{random}.wcnopxkvg.com",
      "https://@{random}.webtanamo.com",
      "https://api.zipdrama.io",
      "https://zipdrama-api.mux-api.com"
    ],
    'ir': [
      "https://d1d4byfyp6zm7b.cloudfront.net",
      "https://dffeid9dlguv5.cloudfront.net",
      "https://d23xbmkdgyrady.cloudfront.net",
      "https://d1f5u82p4z6mfv.cloudfront.net",
      "https://d2pe2j5hv7ngqy.cloudfront.net",
      "https://d154pvmjlg8067.cloudfront.net",
      "https://d31031fstgleqs.cloudfront.net",
      "https://d1fs9fucag5id4.cloudfront.net",
      "https://d2xy3gkefbi597.cloudfront.net",
      "https://d3daddgcsv5z1g.cloudfront.net",
      "https://d2c2w0p8sjz1o7.cloudfront.net",
      "https://dskntn5w2jbb4.cloudfront.net",
      "https://@{random}.wazumor.com",
      "https://@{random}.wberqxan.com",
      "https://api.zipdrama.io",
      "https://zipdrama-api.mux-api.com"
    ],
    fallbackKey: [
      "https://@{random}.frenzol.shop",
      "https://d1d4byfyp6zm7b.cloudfront.net",
      "https://@{random}.jalvora.shop",
      "https://dffeid9dlguv5.cloudfront.net",
      "https://@{random}.krezulo.shop",
      "https://d23xbmkdgyrady.cloudfront.net",
      "https://@{random}.lumqira.shop",
      "https://d1f5u82p4z6mfv.cloudfront.net",
      "https://@{random}.mexlura.shop",
      "https://d2pe2j5hv7ngqy.cloudfront.net",
      "https://d154pvmjlg8067.cloudfront.net",
      "https://d31031fstgleqs.cloudfront.net",
      "https://d1fs9fucag5id4.cloudfront.net",
      "https://d2xy3gkefbi597.cloudfront.net",
      "https://d3daddgcsv5z1g.cloudfront.net",
      "https://d2c2w0p8sjz1o7.cloudfront.net",
      "https://dskntn5w2jbb4.cloudfront.net",
      "https://api.zipdrama.io",
      "https://zipdrama-api.mux-api.com"
    ],
  },
  localLogUrls: {
    'mm': [
      'https://@{random}.polveta.shop',
      'https://@{random}.trunzek.shop',
      'https://@{random}.vorklin.shop',
      'https://@{random}.xandrel.shop',
      'https://@{random}.zontrik.shop',
      'https://d3vwceul3blztx.cloudfront.net',
      'https://d2nfa3kua01rw1.cloudfront.net',
      'https://d2f52d5baj4nl3.cloudfront.net',
      'https://d1xzli91x83k5j.cloudfront.net',
      'https://d2dm46gpvcw51x.cloudfront.net',
      'https://stat.zipdrama.io',
    ],
    'ir': [
      'https://d14x9ghwtxo2h7.cloudfront.net',
      'https://dwzjk8rad3zb8.cloudfront.net',
      'https://dixbbe2oe52co.cloudfront.net',
      'https://dpm9gel9hpfiz.cloudfront.net',
      'https://d2op4cwd3r7685.cloudfront.net',
      'https://dxm84b1j92yj4.cloudfront.net',
      'https://d1tj3p6kh6uobx.cloudfront.net',
      'https://d2l075f13qjtf.cloudfront.net',
      'https://d3cl04bvowkzo9.cloudfront.net',
      'https://d2f52d5baj4nl3.cloudfront.net',
      'https://d1xzli91x83k5j.cloudfront.net',
      'https://d2dm46gpvcw51x.cloudfront.net',
      'https://@{random}.polveta.shop',
      'https://@{random}.trunzek.shop',
      'https://@{random}.vorklin.shop',
      'https://stat.zipdrama.io',
    ],
    fallbackKey: [
      'https://@{random}.polveta.shop',
      'https://d14x9ghwtxo2h7.cloudfront.net',
      'https://@{random}.trunzek.shop',
      'https://dwzjk8rad3zb8.cloudfront.net',
      'https://@{random}.vorklin.shop',
      'https://dixbbe2oe52co.cloudfront.net',
      'https://@{random}.xandrel.shop',
      'https://dpm9gel9hpfiz.cloudfront.net',
      'https://@{random}.zontrik.shop',
      'https://d2op4cwd3r7685.cloudfront.net',
      'https://dxm84b1j92yj4.cloudfront.net',
      'https://d1tj3p6kh6uobx.cloudfront.net',
      'https://d2l075f13qjtf.cloudfront.net',
      'https://d3cl04bvowkzo9.cloudfront.net',
      'https://d2f52d5baj4nl3.cloudfront.net',
      'https://d1xzli91x83k5j.cloudfront.net',
      'https://d2dm46gpvcw51x.cloudfront.net',
      'https://stat.zipdrama.io',
    ],
  },
  backupApiUrls: {
    'mm': [
      'https://drive.usercontent.google.com/download?id=1PT5CN_vg46wL_DVFBNP_8f5Y8AuFlAeG&export=download',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-MM.txt',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-MM.png',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-MM.txt',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-MM.png',
    ],
    'ir': [
      'https://drive.usercontent.google.com/download?id=1n53CYY8UgtIA1H3pH_DddyqCs3SRlgtU&export=download',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-IR.txt',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-IR.png',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-IR.txt',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-IR.png',
    ],
    fallbackKey: [
      'https://drive.usercontent.google.com/download?id=1OwcyxLPaZKjsP7pBzbPqwHNs33GCaTXS&export=download',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-default.txt',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-default.png',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-default.txt',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-default.png',
    ],
  },
);