
const _kReleaseConfigModel = AppConfigModel(
  localApiUrls: {
    'mm': [
      "https://@{random}.vxtklsqhd.com",
      "https://@{random}.vzcumtkhp.com",
      "https://@{random}.vzxcpnmlk.com",
      "https://d36xudtatycawh.cloudfront.net",
      "https://de6ptyo9ugbhx.cloudfront.net",
      "https://dka2yoe4801q8.cloudfront.net",
      "https://da2ofy1ihk5g5.cloudfront.net",
      "https://d21cs5gb4vom6y.cloudfront.net",
      "https://@{random}.wazumor.com",
      "https://@{random}.wberqxan.com",
      "https://@{random}.wbnfqz.com",
      "https://@{random}.wcnopxkvg.com",
      "https://@{random}.webtanamo.com",
      "https://api.zipdrama.io",
      "https://zipdrama-api.mux-api.com"
    ],
    'ir': [
      "https://dnpwax8l7os1n.cloudfront.net",
      "https://dvx05pkvbhoqm.cloudfront.net",
      "https://d3tntmzbloolr2.cloudfront.net",
      "https://d2dd7uwlsw5trk.cloudfront.net",
      "https://d3vakcjfy6dkun.cloudfront.net",
      "https://dmeatgr56uchs.cloudfront.net",
      "https://d3nuvritpfahgt.cloudfront.net",
      "https://d2k0ocz21hd1u9.cloudfront.net",
      "https://d1v6jfqzbxzb8r.cloudfront.net",
      "https://d3amal2b2d0yi5.cloudfront.net",
      "https://du3wqtn7l0573.cloudfront.net",
      "https://d3gw48t2aex5jl.cloudfront.net",
      "https://@{random}.wazumor.com",
      "https://@{random}.wberqxan.com",
      "https://api.zipdrama.io",
      "https://zipdrama-api.mux-api.com"
    ],
    fallbackKey: [
      "https://@{random}.frenzol.shop",
      "https://d3tlb7ggcg8nfx.cloudfront.net",
      "https://@{random}.jalvora.shop",
      "https://d3rb0iubxd3jz8.cloudfront.net",
      "https://@{random}.krezulo.shop",
      "https://d101uf0cr1v7xi.cloudfront.net",
      "https://@{random}.lumqira.shop",
      "https://d25hgjf5p2db0z.cloudfront.net",
      "https://@{random}.mexlura.shop",
      "https://d1bz0hpdaclgfk.cloudfront.net",
      "https://d1bhmc27p0pg16.cloudfront.net",
      "https://dfq2zrkoyvfha.cloudfront.net",
      "https://d1dm4yhm8s0eoy.cloudfront.net",
      "https://d3veclo8tkitdr.cloudfront.net",
      "https://d7cx53pml2upl.cloudfront.net",
      "https://d3vzoqjpcq7tw3.cloudfront.net",
      "https://dqbltip8y554j.cloudfront.net",
      "https://api.zipdrama.io",
      "https://zipdrama-api.mux-api.com"
    ],
  },
  localLogUrls: {
    'mm': [
      'https://@{random}.polveta.shop',
      'https://@{random}.trunzek.shop',
      'https://@{random}.vorklin.shop',
      'https://@{random}.xandrel.shop',
      'https://@{random}.zontrik.shop',
      "https://d1yxuqhbh12pv5.cloudfront.net",
      "https://d2rpcfqcc822qw.cloudfront.net",
      "https://dm5i40p1ze8v5.cloudfront.net",
      "https://d245yvxwoqc7lj.cloudfront.net",
      "https://d3vjhqahi3nd7i.cloudfront.net",
      'https://stat.zipdrama.io',
    ],
    'ir': [
      "https://d251mio0qyc7ax.cloudfront.net",
      "https://dvpd0btkma4ql.cloudfront.net",
      "https://d3h733e841eczg.cloudfront.net",
      "https://d2h1cwu6tm9thp.cloudfront.net",
      "https://d1dgkyzqks60o3.cloudfront.net",
      "https://d4rvbxcoga1bh.cloudfront.net",
      "https://dcnbctfio2ray.cloudfront.net",
      "https://d1o1myaooxaux6.cloudfront.net",
      "https://d26vqqj9x69fi1.cloudfront.net",
      "https://d3lqy2qt5bjich.cloudfront.net",
      "https://d2f4cfb0ljba53.cloudfront.net",
      "https://d1xhlu4z82ujo.cloudfront.net",
      'https://@{random}.polveta.shop',
      'https://@{random}.trunzek.shop',
      'https://@{random}.vorklin.shop',
      'https://stat.zipdrama.io',
    ],
    fallbackKey: [
      'https://@{random}.polveta.shop',
      "https://d3a5jtcmw2ldkp.cloudfront.net",
      'https://@{random}.trunzek.shop',
      "https://dmetepowskee8.cloudfront.net",
      'https://@{random}.vorklin.shop',
      "https://d2vx40ak52sbbe.cloudfront.net",
      'https://@{random}.xandrel.shop',
      "https://du1obi7hoy2nw.cloudfront.net",
      'https://@{random}.zontrik.shop',
      "https://d1f0srhys6t91e.cloudfront.net",
      "https://d27k9a15xkht56.cloudfront.net",
      "https://d2wj74vt8uqw9z.cloudfront.net",
      "https://dvczh9ibyo4pm.cloudfront.net",
      "https://d38p8b7ltcmht4.cloudfront.net",
      "https://d2to5in2cprab2.cloudfront.net",
      "https://d16efypmxsqli3.cloudfront.net",
      "https://d300ph3j1m7y9i.cloudfront.net",
      'https://stat.zipdrama.io',
    ],
  },
  backupApiUrls: {
    'mm': [
      'https://drive.usercontent.google.com/download?id=1PT5CN_vg46wL_DVFBNP_8f5Y8AuFlAeG&export=download',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-MM.txt',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-MM.png',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-MM.txt',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-MM.png',
    ],
    'ir': [
      'https://drive.usercontent.google.com/download?id=1n53CYY8UgtIA1H3pH_DddyqCs3SRlgtU&export=download',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-IR.txt',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-IR.png',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-IR.txt',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-IR.png',
    ],
    fallbackKey: [
      'https://drive.usercontent.google.com/download?id=1OwcyxLPaZKjsP7pBzbPqwHNs33GCaTXS&export=download',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-default.txt',
      'https://raw.githubusercontent.com/vediozd/legendary-eureka/refs/heads/main/PDGC-PRO/API-default.png',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-default.txt',
      'https://github.com/vediozd/legendary-eureka/releases/download/v0.2/API-default.png',
    ],
  },
);